version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

    environment:
      - FLASK_ENV=${FLASK_ENV}
      - APP_SETTINGS=config.config.Config
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tictactoe_network
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - tictactoe_network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - FLASK_ENV=testing
      - APP_SETTINGS=config.config.TestingConfig
      - TEST_DB_NAME=${TEST_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db_test
    networks:
      - tictactoe_test_network
    volumes:
      - .:/app

  db_test:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${TEST_DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - tictactoe_test_network
    volumes:
      - db_test_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  tictactoe_network:
    driver: bridge
  tictactoe_test_network:
    driver: bridge

volumes:
  db_data:
  db_test_data:
